### PR TITLE
Prac 6 code review request

### PR DESCRIPTION
**Pull request by Blake0982**
Prac 6 code review request @Dallas-Mutch
review code for errors and possible improvements
have a good one 👍

### CODE REVIEW

**Review by Dallas-Mutch — COMMENTED** [review]
Code works and did not find any errors. I like having that function for limo to separate for my car.

**Review by Dallas-Mutch — COMMENTED** [review]
No errors found in the code. 
looking at the testing though, i was expecting to a test to see if the two guitars were aged correctly with 100 gibson and 9 for another guitar. the 100 at the end of the line did not make sense, if it was in line with the guitar with context like "Gibson age expecting 100(typed). got 100(code)".
I enjoyed the way you broke up each problem with a function on the guitars, it provided better viewing.
There are better ways to do the get_age and is_vintage with using them in a single sentence each.
get_age = return current_year - self.year
is_vintage = return self.get_age() >= 50
overall, the code was well put together and understood everything except for the testing.

**Review by Dallas-Mutch — COMMENTED** [review]
Everything works, no errors i can see. nothing i can think of that needs improving.

**Comment by Blake0982** [comment]
thank you for the review 👍

**Pull request merged**
